Slack: Feature - Adding get channel and archive channel actions
splunk-soar-connectors/slack pull request #36
Opened 2024-12-02 19:24 UTC by jumpleby-splunk

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features) 
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- Adding a get channel function to be able to search for a splunk channel ID by name, or also return full channel information via channel ID
- Adding an archive channel function to be able to archive channels automatically via playbook capability

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.
described in release notes - archive and get channel functions

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2025-01-18 08:06 UTC, phantom-jacob requested changes

2025-01-18 08:06 UTC, phantom-jacob commented on slack_connector.py
> +        if (searchbyname == False) and (searchbyid == False):
Nit:

```suggestion
        if not (searchbyname or searchbyid):
```

2025-01-18 08:06 UTC, phantom-jacob commented on slack_connector.py
> +            return action_result.set_status(phantom.APP_ERROR)
We can give the user more info here

```suggestion
            return action_result.set_status(phantom.APP_ERROR, "Must search by one of IDs or names")
```

2025-01-18 08:06 UTC, phantom-jacob commented on slack_connector.py
> +                return action_result.get_status()
Can we put more info in this failure path?

2025-01-18 08:06 UTC, phantom-jacob commented on slack_connector.py
> +            return ret_val
Can we put some info in this failure path?

2025-01-21 20:39 UTC, jumpleby-splunk commented on slack_connector.py
> +                return action_result.get_status()
ok updated the code to reflect this request

2025-01-21 20:39 UTC, jumpleby-splunk commented on slack_connector.py
> +            return ret_val
ok updated the code to reflect this request

2025-02-24 22:10 UTC, phantom-jacob approved these changes

2025-02-24 22:10 UTC, merged